export const getStyles = (theme) => ({
  titlePage: {
    fontSize: "1.125rem",
    fontWeight: 600,
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    overflow: "hidden",
    color: theme.color,
    borderBottom: `2px solid ${theme.accent}`,
    paddingBottom: theme.spacing.sm,
    transition: "color 0.3s ease, border-color 0.3s ease",
  },
  title: {
    fontSize: "0.965rem",
    fontWeight: 500,
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    overflow: "hidden",
    color: theme.color,
    transition: "color 0.3s ease",
  },
  textFaq: {
    background: "none  !important",
    backgroundColor: "transparent !important",
    color: theme.color,
    fontSize: "14px",
    width: "100%",
    overflow: "auto",
    wordWrap: "break-word",
    whiteSpace: "normal",
    lineHeight: 1.5,
    textRendering: "optimizeLegibility",
    fontWeight: "400",
    letterSpacing: "0.00988em",
    textAlign: "justify",
    display: "block",
    margin: "10px 0",
    transition: "color 0.3s ease",
  },
  subTitle: {
    fontSize: "0.665rem",
    fontWeight: 500,
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    overflow: "hidden",
    color: theme.color,
    transition: "color 0.3s ease",
  },
});
