export const getStyles = (theme, showList, isMobile, isHovered) => ({
  container: {
    maxWidth: "100vw",
    height: "100vh",
    overflow: "hidden",
    background: theme.backgroundD,
    transition: "background 0.3s ease",
    display: "flex",
    flexDirection: "column",
  },
  nav: {
    background: theme.backgroundL,
    transition: "background 0.3s ease",
    flexShrink: 0,
  },
  listdetail: {
    marginTop: "16px",
    display: "flex",
    padding: "10px",
    gap: showList ? "16px" : "0px",
    flex: 1,
    minHeight: 0,
    background: theme.backgroundD,
  },
  listdetailKanban: {
    minWidth: 300,
    flexShrink: 0,
    gap: "0px",
    minHeight: 0,
    background: theme.backgroundL,
  },
  list: {
    background: theme.backgroundD,
    transition: "background 0.3s ease, width 0.6s ease, opacity 0.6s ease",
    width: isMobile ? (showList ? "100%" : "0px") : showList ? "35%" : "0px",
    opacity: showList ? 1 : 0,
    overflowY: "scroll",
    marginLeft: "16px",
    borderRadius: theme.borderRadius.xl,
    padding: theme.spacing.sm,
  },
  listForm: {
    background: theme.backgroundL,
    width: isMobile ? "0" : "35%",
    padding: isMobile
      ? showList
        ? "0 5px"
        : "0px"
      : showList
        ? "0 5px"
        : "0px",
    opacity: showList ? 1 : 0,
    transition:
      "background 0.3s ease, width 0.6s ease, opacity 0.6s ease, padding 0.6s ease",
    overflowY: "hidden",
    height: "95%",
    margin: "1%",
    borderRadius: theme.borderRadius.xl,
  },
  logo: {
    maxHeight: "100%",
    width: "100%",
    // filter: "grayscale(120%)",
  },
  detail: {
    background: theme.backgroundD,
    width: isMobile ? (showList ? "0px" : "100%") : showList ? "65%" : "100%",
    padding: theme.spacing.sm,
    transition: "background 0.3s ease, width 0.6s ease",
    overflowY: "scroll",
    // marginLeft: "0px",
    margin: "1% 16px 1% -8px",
    borderRadius: theme.borderRadius.xl,
  },
  onlyDetail: {
    background: theme.backgroundL,
    width: "100%",
    padding: theme.spacing.sm,
    transition: "background 0.3s ease, width 0.6s ease",
    overflowY: "scroll",
    // marginLeft: "0px",
    margin: "1%",
    borderRadius: theme.borderRadius.xl,
  },
  toggleButton: {
    position: "absolute",
    left: isMobile ? (showList ? "90%" : "0px") : showList ? "35%" : "0px",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 10,
    background: isHovered ? theme.accent : theme.backgroundL,
    borderRadius: theme.borderRadius.md,
    padding: `${theme.spacing.xs} ${theme.spacing.sm}`,
    cursor: "pointer",
    color: isHovered ? "#FFFFFF" : theme.color,
    transition: "all 0.3s ease",
    marginLeft: "-2px",
    boxShadow: theme.shadow.sm,
    border: `1px solid ${isHovered ? theme.accent : theme.borderColor}30`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    opacity: isHovered ? 1 : 0.6,
    "&:hover": {
      boxShadow: theme.shadow.md,
    },
  },
  downloadFooter: {
    background: theme.backgroundL,
    minHeight: "40px",
    maxHeight: "350px",
    overflowY: "auto",
    borderTop: `1px solid ${theme.borderColor}`,
    transition:
      "background 0.3s ease, border-color 0.3s ease, max-height 0.3s ease",
    flexShrink: 0,
  },
  footer: {
    background: theme.backgroundL,
    height: "25px",
    borderTop: `1px solid ${theme.borderColor}`,
    transition: "background 0.3s ease, border-color 0.3s ease",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
});
