import { width } from "@mui/system";

export const getStyles = (theme, grupo) => ({
  accordion: {
    background: theme.backgroundL,
    border: "none",
    padding: `${theme.spacing.sm} ${theme.spacing.sm}`,
    marginBottom: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
    boxShadow: "none",
    transition: "all 0.2s ease, background 0.3s ease",
  },
  container: {
    background: theme.backgroundD,
    color: theme.color,
    padding: `${theme.spacing.sm} ${theme.spacing.md}`,
    marginBottom: theme.spacing.xs,
    borderRadius: theme.borderRadius.md,
    border: "none",
    transition: "background 0.3s ease, color 0.3s ease",
  },
  accordionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    cursor: "pointer",
    color: theme.color,
    padding: `${theme.spacing.xs} 0 0 0`,
    borderRadius: theme.borderRadius.sm,
    transition: "all 0.2s ease, color 0.3s ease",
  },
  title: {
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.semibold,
    whiteSpace: "nowrap",
    width: "100%",
    textOverflow: "ellipsis",
    overflow: "hidden",
    lineHeight: "1.4",
  },
  accordionDetails: {
    overflow: "hidden",
    transition: "max-height 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    background: "inherit",
    padding: `${theme.spacing.xs} 0`,
    borderRadius: theme.borderRadius.sm,
  },
  detailsKanban: {
    display: "flex", 
    flexDirection: "column",
    overflow: "hidden",
    transition: "max-height 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    background: "inherit",
    // padding: `${theme.spacing.xs} 0 `,
    width: '100%',
    borderRadius: theme.borderRadius.sm,
    maxHeight: visualViewport.height - 310,
    overflowY: "auto",
    flex: 1,
  },
});
