export const listBlocos = [
  {
    numero: 1,
    empresa: 1,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: null,
    serrada: "OK",
    envelopamento: "OK",
    carregamento: "10/10/2025",
    frete: "WD",
  },
  {
    numero: 2,
    empresa: 2,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: "CS3",
    serrada: null,
    envelopamento: "OK",
    carregamento: "11/10/2025",
    frete: "WD",
  },
  {
    numero: 3,
    empresa: 3,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: null,
    serrada: null,
    envelopamento: "OK",
    carregamento: null,
    frete: null,
  },
  {
    numero: 4,
    empresa: 1,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "IMARF",
    venda: null,
    serrada: null,
    envelopamento: null,
    carregamento: null,
    frete: null,
  },
  {
    numero: 5,
    empresa: 2,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: "CS3",
    serrada: "OK",
    envelopamento: "OK",
    carregamento: "12/10/2025",
    frete: "WD",
  },
  {
    numero: 6,
    empresa: 3,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "IMARF",
    venda: null,
    serrada: "OK",
    envelopamento: null,
    carregamento: "13/10/2025",
    frete: null,
  },
  {
    numero: 7,
    empresa: 1,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: null,
    serrada: null,
    envelopamento: "OK",
    carregamento: null,
    frete: "WD",
  },
  {
    numero: 8,
    empresa: 2,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "IMARF",
    venda: "CS3",
    serrada: "OK",
    envelopamento: "OK",
    carregamento: "14/10/2025",
    frete: "WD",
  },
  {
    numero: 9,
    empresa: 3,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: null,
    serrada: null,
    envelopamento: null,
    carregamento: null,
    frete: null,
  },
  {
    numero: 10,
    empresa: 1,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "IMARF",
    venda: "CS3",
    serrada: "OK",
    envelopamento: "OK",
    carregamento: "15/10/2025",
    frete: "WD",
  },
  {
    numero: 11,
    empresa: 2,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: null,
    serrada: "OK",
    envelopamento: null,
    carregamento: null,
    frete: "WD",
  },
  {
    numero: 12,
    empresa: 3,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "IMARF",
    venda: null,
    serrada: null,
    envelopamento: "OK",
    carregamento: "16/10/2025",
    frete: null,
  },
  {
    numero: 13,
    empresa: 1,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: "CS3",
    serrada: "OK",
    envelopamento: "OK",
    carregamento: "17/10/2025",
    frete: "WD",
  },
  {
    numero: 14,
    empresa: 2,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "IMARF",
    venda: null,
    serrada: "OK",
    envelopamento: null,
    carregamento: null,
    frete: "WD",
  },
  {
    numero: 15,
    empresa: 3,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: null,
    serrada: null,
    envelopamento: "OK",
    carregamento: "18/10/2025",
    frete: null,
  },
  {
    numero: 16,
    empresa: 1,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "IMARF",
    venda: "CS3",
    serrada: "OK",
    envelopamento: "OK",
    carregamento: "19/10/2025",
    frete: "WD",
  },
  {
    numero: 17,
    empresa: 2,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: null,
    serrada: null,
    envelopamento: null,
    carregamento: null,
    frete: null,
  },
  {
    numero: 18,
    empresa: 3,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "IMARF",
    venda: null,
    serrada: "OK",
    envelopamento: "OK",
    carregamento: "20/10/2025",
    frete: "WD",
  },
  {
    numero: 19,
    empresa: 1,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "CALVI",
    venda: "CS3",
    serrada: "OK",
    envelopamento: null,
    carregamento: null,
    frete: "WD",
  },
  {
    numero: 20,
    empresa: 2,
    medidas_brutas: { largura: 1.0, altura: 1.0, comprimento: 1.0, m3: 1.0 },
    medidas_liquidas: { largura: 0.9, altura: 0.9, comprimento: 0.9, m3: 0.73 },
    marcacao: "IMARF",
    venda: null,
    serrada: null,
    envelopamento: "OK",
    carregamento: "21/10/2025",
    frete: null,
  },
];
